# Generated by Django 5.2.1 on 2025-06-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_type',
        ),
        migrations.AddField(
            model_name='qualification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
